package mc.arch.minigames.pof.loadout

import com.cryptomorin.xseries.XEnchantment
import com.cryptomorin.xseries.XMaterial
import com.cryptomorin.xseries.XPotion
import org.bukkit.Material
import org.bukkit.inventory.ItemStack

object ModernPofLootTable : PofLootTable()
{
    override val commonSpec: List<Pair<XMaterial, Int>> = listOf(
        XMaterial.OAK_PLANKS to 8,
        XMaterial.SPRUCE_PLANKS to 8,
        XMaterial.BIRCH_PLANKS to 8,
        XMaterial.JUNGLE_PLANKS to 8,
        XMaterial.ACACIA_PLANKS to 8,
        XMaterial.DARK_OAK_PLANKS to 8,
        XMaterial.COBBLESTONE to 12,
        XMaterial.STONE to 8,
        XMaterial.DIRT to 16,
        XMaterial.SAND to 8,
        XMaterial.SANDSTONE to 6,
        XMaterial.GRAVEL to 6,
        XMaterial.NETHERRACK to 16,
        XMaterial.WOODEN_SWORD to 1,
        XMaterial.STONE_SWORD to 1,
        XMaterial.WOODEN_AXE to 1,
        XMaterial.WOODEN_PICKAXE to 1,
        XMaterial.STONE_PICKAXE to 1,
        XMaterial.ARROW to 4,
        XMaterial.APPLE to 2,
        XMaterial.BREAD to 3,
        XMaterial.COOKED_BEEF to 2,
        XMaterial.COOKED_CHICKEN to 2,
        XMaterial.LADDER to 6,
        XMaterial.STICK to 4,
        XMaterial.LEATHER_HELMET to 1,
        XMaterial.LEATHER_CHESTPLATE to 1,
        XMaterial.LEATHER_LEGGINGS to 1,
        XMaterial.LEATHER_BOOTS to 1,
        XMaterial.COBWEB to 1,
        XMaterial.FIRE_CHARGE to 2,
        XMaterial.PUMPKIN to 1
    )

    override val uncommonSpec: List<Pair<XMaterial, Int>> = listOf(
        XMaterial.IRON_SWORD to 1,
        XMaterial.IRON_AXE to 1,
        XMaterial.IRON_PICKAXE to 1,
        XMaterial.BOW to 1,
        XMaterial.ARROW to 8,
        XMaterial.FISHING_ROD to 1,
        XMaterial.OBSIDIAN to 4,
        XMaterial.IRON_BLOCK to 1,
        XMaterial.WHITE_WOOL to 16,
        XMaterial.RED_WOOL to 8,
        XMaterial.BLUE_WOOL to 8,
        XMaterial.YELLOW_WOOL to 8,
        XMaterial.GREEN_WOOL to 8,
        XMaterial.GLASS to 8,
        XMaterial.GLOWSTONE to 4,
        XMaterial.IRON_HELMET to 1,
        XMaterial.IRON_CHESTPLATE to 1,
        XMaterial.IRON_LEGGINGS to 1,
        XMaterial.IRON_BOOTS to 1,
        XMaterial.CHAINMAIL_HELMET to 1,
        XMaterial.CHAINMAIL_CHESTPLATE to 1,
        XMaterial.CHAINMAIL_LEGGINGS to 1,
        XMaterial.CHAINMAIL_BOOTS to 1,
        XMaterial.GOLDEN_SWORD to 1,
        XMaterial.GOLDEN_APPLE to 1,
        XMaterial.MUSHROOM_STEW to 1,
        XMaterial.PUMPKIN_PIE to 2,
        XMaterial.OAK_SLAB to 16,
        XMaterial.OAK_STAIRS to 16,
        XMaterial.OAK_FENCE to 8,
        XMaterial.STONE_BRICKS to 8,
        XMaterial.STONE_PRESSURE_PLATE to 4,
        XMaterial.STONE_BUTTON to 4,
        XMaterial.OAK_PRESSURE_PLATE to 4,
        XMaterial.OAK_BUTTON to 4,
        XMaterial.WHITE_CARPET to 4,
        XMaterial.RED_CARPET to 4,
        XMaterial.WHITE_BANNER to 1,
        XMaterial.RED_BANNER to 1,
        XMaterial.BLUE_BANNER to 1,
        XMaterial.COBWEB to 2,
        XMaterial.VEX_SPAWN_EGG to 1,
        XMaterial.BAT_SPAWN_EGG to 1,
        XMaterial.CHICKEN_SPAWN_EGG to 1,
        XMaterial.WATER_BUCKET to 1,
        XMaterial.SLIME_BLOCK to 4,
        XMaterial.HAY_BLOCK to 4,
        XMaterial.ENDER_PEARL to 1,
        XMaterial.WIND_CHARGE to 2,
        XMaterial.PIG_SPAWN_EGG to 1,
        XMaterial.COW_SPAWN_EGG to 1,
        XMaterial.SHEEP_SPAWN_EGG to 1,
        XMaterial.CREEPER_SPAWN_EGG to 1,
        XMaterial.ZOMBIE_SPAWN_EGG to 1,
        XMaterial.SKELETON_SPAWN_EGG to 1,
        XMaterial.SPIDER_SPAWN_EGG to 1,
        XMaterial.SLIME_SPAWN_EGG to 1,
        XMaterial.HUSK_SPAWN_EGG to 1,
        XMaterial.CAVE_SPIDER_SPAWN_EGG to 1,
        XMaterial.ANVIL to 1,
        XMaterial.HONEY_BLOCK to 3,
        XMaterial.SHIELD to 1
    )

    override val uncommonExtras: List<ItemStack> = listOf(
        knockbackStick(1),
        splashPotion(XPotion.POISON, durationTicks = 200, level = 0),
        splashPotion(XPotion.WEAKNESS, durationTicks = 300, level = 0)
    )

    override val rareSpec: List<Pair<XMaterial, Int>> = listOf(
        XMaterial.DIAMOND_SWORD to 1,
        XMaterial.DIAMOND_AXE to 1,
        XMaterial.DIAMOND_PICKAXE to 1,
        XMaterial.DIAMOND_HELMET to 1,
        XMaterial.DIAMOND_CHESTPLATE to 1,
        XMaterial.DIAMOND_LEGGINGS to 1,
        XMaterial.DIAMOND_BOOTS to 1,
        XMaterial.ENCHANTED_GOLDEN_APPLE to 1,
        XMaterial.ENDER_PEARL to 3,
        XMaterial.GOLDEN_APPLE to 2,
        XMaterial.TNT to 2,
        XMaterial.FLINT_AND_STEEL to 1,
        XMaterial.BOW to 1,
        XMaterial.ARROW to 16,
        XMaterial.OBSIDIAN to 8,
        XMaterial.MACE to 1,
        XMaterial.TRIDENT to 1,
        XMaterial.WITHER_SKELETON_SPAWN_EGG to 1,
        XMaterial.BLAZE_SPAWN_EGG to 1,
        XMaterial.ENDERMAN_SPAWN_EGG to 1,
        XMaterial.WITCH_SPAWN_EGG to 1,
        XMaterial.BREEZE_SPAWN_EGG to 1,
        XMaterial.PHANTOM_SPAWN_EGG to 1,
        XMaterial.DROWNED_SPAWN_EGG to 1,
        XMaterial.LAVA_BUCKET to 1,
        XMaterial.TOTEM_OF_UNDYING to 1,
        XMaterial.TNT_MINECART to 1,
        XMaterial.ELYTRA to 1
    )

    override val rareExtras: List<ItemStack> = listOf(
        knockbackStick(2),
        maceWithWindBurst(2),
        splashPotion(XPotion.SLOW_FALLING, durationTicks = 600, level = 0),
        splashPotion(XPotion.SPEED, durationTicks = 600, level = 1),
        splashPotion(XPotion.INSTANT_DAMAGE, durationTicks = 1, level = 1),
        splashPotion(XPotion.POISON, durationTicks = 800, level = 1)
    )

    override val junkSpec: List<Pair<XMaterial, Int>> = listOf(
        XMaterial.PAPER to 4,
        XMaterial.STICK to 8,
        XMaterial.STRING to 4,
        XMaterial.FEATHER to 4,
        XMaterial.BONE to 4,
        XMaterial.ROTTEN_FLESH to 4,
        XMaterial.SPIDER_EYE to 1,
        XMaterial.LEATHER to 4,
        XMaterial.BRICK to 4,
        XMaterial.CLAY_BALL to 4,
        XMaterial.FLOWER_POT to 1,
        XMaterial.WHEAT_SEEDS to 4,
        XMaterial.PUMPKIN_SEEDS to 4,
        XMaterial.MELON_SEEDS to 4,
        XMaterial.RED_DYE to 4,
        XMaterial.GREEN_DYE to 4,
        XMaterial.BLUE_DYE to 4,
        XMaterial.YELLOW_DYE to 4,
        XMaterial.BLACK_DYE to 4,
        XMaterial.WHITE_DYE to 4,
        XMaterial.MUSIC_DISC_13 to 1,
        XMaterial.MUSIC_DISC_CAT to 1,
        XMaterial.MUSIC_DISC_BLOCKS to 1,
        XMaterial.MUSIC_DISC_CHIRP to 1,
        XMaterial.MUSIC_DISC_FAR to 1,
        XMaterial.MUSIC_DISC_MALL to 1,
        XMaterial.MUSIC_DISC_MELLOHI to 1,
        XMaterial.MUSIC_DISC_STAL to 1,
        XMaterial.MUSIC_DISC_STRAD to 1,
        XMaterial.MUSIC_DISC_WAIT to 1,
        XMaterial.MUSIC_DISC_WARD to 1,
        XMaterial.NAUTILUS_SHELL to 1,
        XMaterial.HEART_OF_THE_SEA to 1,
        XMaterial.RABBIT_HIDE to 4,
        XMaterial.RABBIT_FOOT to 1,
        XMaterial.GHAST_TEAR to 1,
        XMaterial.BLAZE_POWDER to 1,
        XMaterial.BLAZE_ROD to 1,
        XMaterial.GLOW_INK_SAC to 1,
        XMaterial.INK_SAC to 1,
        XMaterial.GUNPOWDER to 1,
        XMaterial.SUGAR to 4,
        XMaterial.GLASS_BOTTLE to 1,
        XMaterial.BOWL to 4,
        XMaterial.NAME_TAG to 1,
        XMaterial.ITEM_FRAME to 1,
        XMaterial.PAINTING to 1,
        XMaterial.LEAD to 1,
        XMaterial.SADDLE to 1,
        XMaterial.BOOK to 4,
        XMaterial.WRITABLE_BOOK to 1,
        XMaterial.MAP to 1,
        XMaterial.COMPASS to 1,
        XMaterial.CLOCK to 1,
        XMaterial.RECOVERY_COMPASS to 1,
        XMaterial.ANGLER_POTTERY_SHERD to 1,
        XMaterial.ARCHER_POTTERY_SHERD to 1,
        XMaterial.ARMS_UP_POTTERY_SHERD to 1,
        XMaterial.BLADE_POTTERY_SHERD to 1,
        XMaterial.BREWER_POTTERY_SHERD to 1,
        XMaterial.BURN_POTTERY_SHERD to 1,
        XMaterial.DANGER_POTTERY_SHERD to 1,
        XMaterial.EXPLORER_POTTERY_SHERD to 1,
        XMaterial.FRIEND_POTTERY_SHERD to 1,
        XMaterial.HEART_POTTERY_SHERD to 1,
        XMaterial.HEARTBREAK_POTTERY_SHERD to 1,
        XMaterial.HOWL_POTTERY_SHERD to 1,
        XMaterial.MINER_POTTERY_SHERD to 1,
        XMaterial.MOURNER_POTTERY_SHERD to 1,
        XMaterial.PLENTY_POTTERY_SHERD to 1,
        XMaterial.PRIZE_POTTERY_SHERD to 1,
        XMaterial.SHEAF_POTTERY_SHERD to 1,
        XMaterial.SHELTER_POTTERY_SHERD to 1,
        XMaterial.SKULL_POTTERY_SHERD to 1,
        XMaterial.SNORT_POTTERY_SHERD to 1
    )

    private fun maceWithWindBurst(level: Int): ItemStack
    {
        val item = XMaterial.MACE.parseItem() ?: return ItemStack(Material.STICK)
        val meta = item.itemMeta ?: return item
        val enchant = XEnchantment.WIND_BURST.get() ?: return item
        meta.addEnchant(enchant, level, true)
        item.itemMeta = meta
        return item
    }
}
